// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: overview.sql

package overviewdb

import (
	"context"
	"encoding/json"
	"time"

	uuid "github.com/gofrs/uuid/v5"
)

const countWorkouts = `-- name: CountWorkouts :one
SELECT count(*) FROM workouts
`

func (q *Queries) CountWorkouts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkouts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const recentWorkouts = `-- name: RecentWorkouts :many
SELECT w.id, w.name, w.started, w.ended, w.planned_session_id,
       coalesce(array_agg(we.name ORDER BY we.position) FILTER (WHERE we.name IS NOT NULL), '{}')::text[] AS exercises
FROM workouts w
LEFT JOIN workout_exercises we ON we.workout_id = w.id
GROUP BY w.id
ORDER BY w.started DESC
LIMIT $1
`

type RecentWorkoutsRow struct {
	ID               uuid.UUID
	Name             string
	Started          time.Time
	Ended            *time.Time
	PlannedSessionID *uuid.UUID
	Exercises        []string
}

func (q *Queries) RecentWorkouts(ctx context.Context, limit int32) ([]RecentWorkoutsRow, error) {
	rows, err := q.db.Query(ctx, recentWorkouts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentWorkoutsRow{}
	for rows.Next() {
		var i RecentWorkoutsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Started,
			&i.Ended,
			&i.PlannedSessionID,
			&i.Exercises,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const settings = `-- name: Settings :many
SELECT key, value FROM settings WHERE key = ANY($1::text[])
`

type SettingsRow struct {
	Key   string
	Value json.RawMessage
}

func (q *Queries) Settings(ctx context.Context, keys []string) ([]SettingsRow, error) {
	rows, err := q.db.Query(ctx, settings, keys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SettingsRow{}
	for rows.Next() {
		var i SettingsRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const username = `-- name: Username :one
SELECT username FROM auth.users WHERE id = $1
`

func (q *Queries) Username(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, username, id)
	var username string
	err := row.Scan(&username)
	return username, err
}
