// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: diary.sql

package diarydb

import (
	"context"
	"time"

	uuid "github.com/gofrs/uuid/v5"
)

const activitiesBetween = `-- name: ActivitiesBetween :many
SELECT id, user_id, day, label, kcal, workout_id, logged_by, created_at FROM activities
WHERE day BETWEEN $1 AND $2
ORDER BY day, created_at, id
`

type ActivitiesBetweenParams struct {
	FromDay time.Time
	ToDay   time.Time
}

func (q *Queries) ActivitiesBetween(ctx context.Context, arg ActivitiesBetweenParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, activitiesBetween, arg.FromDay, arg.ToDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Day,
			&i.Label,
			&i.Kcal,
			&i.WorkoutID,
			&i.LoggedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createActivity = `-- name: CreateActivity :one
INSERT INTO activities (day, label, kcal, workout_id, logged_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, day, label, kcal, workout_id, logged_by, created_at
`

type CreateActivityParams struct {
	Day       time.Time
	Label     string
	Kcal      int32
	WorkoutID *uuid.UUID
	LoggedBy  string
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, createActivity,
		arg.Day,
		arg.Label,
		arg.Kcal,
		arg.WorkoutID,
		arg.LoggedBy,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Day,
		&i.Label,
		&i.Kcal,
		&i.WorkoutID,
		&i.LoggedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createEntry = `-- name: CreateEntry :one
INSERT INTO food_entries (day, meal, food_id, lmv_number, name, grams, amount, kcal, protein, carbs, fat,
                          fiber, sugars, saturated_fat, salt, logged_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, user_id, day, meal, food_id, lmv_number, name, grams, amount, kcal, protein, carbs, fat, fiber, sugars, saturated_fat, salt, logged_by, created_at
`

type CreateEntryParams struct {
	Day          time.Time
	Meal         string
	FoodID       *uuid.UUID
	LmvNumber    *int32
	Name         string
	Grams        float64
	Amount       string
	Kcal         float64
	Protein      float64
	Carbs        float64
	Fat          float64
	Fiber        *float64
	Sugars       *float64
	SaturatedFat *float64
	Salt         *float64
	LoggedBy     string
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (FoodEntry, error) {
	row := q.db.QueryRow(ctx, createEntry,
		arg.Day,
		arg.Meal,
		arg.FoodID,
		arg.LmvNumber,
		arg.Name,
		arg.Grams,
		arg.Amount,
		arg.Kcal,
		arg.Protein,
		arg.Carbs,
		arg.Fat,
		arg.Fiber,
		arg.Sugars,
		arg.SaturatedFat,
		arg.Salt,
		arg.LoggedBy,
	)
	var i FoodEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Day,
		&i.Meal,
		&i.FoodID,
		&i.LmvNumber,
		&i.Name,
		&i.Grams,
		&i.Amount,
		&i.Kcal,
		&i.Protein,
		&i.Carbs,
		&i.Fat,
		&i.Fiber,
		&i.Sugars,
		&i.SaturatedFat,
		&i.Salt,
		&i.LoggedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteActivity = `-- name: DeleteActivity :execrows
DELETE FROM activities WHERE id = $1
`

func (q *Queries) DeleteActivity(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteActivity, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEntry = `-- name: DeleteEntry :execrows
DELETE FROM food_entries WHERE id = $1
`

func (q *Queries) DeleteEntry(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEntry, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWeight = `-- name: DeleteWeight :execrows
DELETE FROM body_weights WHERE day = $1
`

func (q *Queries) DeleteWeight(ctx context.Context, day time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWeight, day)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const entriesBetween = `-- name: EntriesBetween :many

SELECT id, user_id, day, meal, food_id, lmv_number, name, grams, amount, kcal, protein, carbs, fat, fiber, sugars, saturated_fat, salt, logged_by, created_at FROM food_entries
WHERE day BETWEEN $1 AND $2
ORDER BY day, created_at, id
`

type EntriesBetweenParams struct {
	FromDay time.Time
	ToDay   time.Time
}

// Row level security scopes every query to the signed in user.
func (q *Queries) EntriesBetween(ctx context.Context, arg EntriesBetweenParams) ([]FoodEntry, error) {
	rows, err := q.db.Query(ctx, entriesBetween, arg.FromDay, arg.ToDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FoodEntry{}
	for rows.Next() {
		var i FoodEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Day,
			&i.Meal,
			&i.FoodID,
			&i.LmvNumber,
			&i.Name,
			&i.Grams,
			&i.Amount,
			&i.Kcal,
			&i.Protein,
			&i.Carbs,
			&i.Fat,
			&i.Fiber,
			&i.Sugars,
			&i.SaturatedFat,
			&i.Salt,
			&i.LoggedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntry = `-- name: GetEntry :one
SELECT id, user_id, day, meal, food_id, lmv_number, name, grams, amount, kcal, protein, carbs, fat, fiber, sugars, saturated_fat, salt, logged_by, created_at FROM food_entries WHERE id = $1
`

func (q *Queries) GetEntry(ctx context.Context, id uuid.UUID) (FoodEntry, error) {
	row := q.db.QueryRow(ctx, getEntry, id)
	var i FoodEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Day,
		&i.Meal,
		&i.FoodID,
		&i.LmvNumber,
		&i.Name,
		&i.Grams,
		&i.Amount,
		&i.Kcal,
		&i.Protein,
		&i.Carbs,
		&i.Fat,
		&i.Fiber,
		&i.Sugars,
		&i.SaturatedFat,
		&i.Salt,
		&i.LoggedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getGoal = `-- name: GetGoal :one
SELECT user_id, direction, kcal, protein, carbs, fat, add_activities, target_weight, weekly_change, notes, updated_at FROM nutrition_goals
`

func (q *Queries) GetGoal(ctx context.Context) (NutritionGoal, error) {
	row := q.db.QueryRow(ctx, getGoal)
	var i NutritionGoal
	err := row.Scan(
		&i.UserID,
		&i.Direction,
		&i.Kcal,
		&i.Protein,
		&i.Carbs,
		&i.Fat,
		&i.AddActivities,
		&i.TargetWeight,
		&i.WeeklyChange,
		&i.Notes,
		&i.UpdatedAt,
	)
	return i, err
}

const saveGoal = `-- name: SaveGoal :one
INSERT INTO nutrition_goals (direction, kcal, protein, carbs, fat, add_activities, target_weight,
                             weekly_change, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (user_id) DO UPDATE
SET direction = excluded.direction, kcal = excluded.kcal, protein = excluded.protein,
    carbs = excluded.carbs, fat = excluded.fat, add_activities = excluded.add_activities,
    target_weight = excluded.target_weight, weekly_change = excluded.weekly_change,
    notes = excluded.notes, updated_at = now()
RETURNING user_id, direction, kcal, protein, carbs, fat, add_activities, target_weight, weekly_change, notes, updated_at
`

type SaveGoalParams struct {
	Direction     string
	Kcal          int32
	Protein       int32
	Carbs         int32
	Fat           int32
	AddActivities bool
	TargetWeight  *float64
	WeeklyChange  *float64
	Notes         string
}

func (q *Queries) SaveGoal(ctx context.Context, arg SaveGoalParams) (NutritionGoal, error) {
	row := q.db.QueryRow(ctx, saveGoal,
		arg.Direction,
		arg.Kcal,
		arg.Protein,
		arg.Carbs,
		arg.Fat,
		arg.AddActivities,
		arg.TargetWeight,
		arg.WeeklyChange,
		arg.Notes,
	)
	var i NutritionGoal
	err := row.Scan(
		&i.UserID,
		&i.Direction,
		&i.Kcal,
		&i.Protein,
		&i.Carbs,
		&i.Fat,
		&i.AddActivities,
		&i.TargetWeight,
		&i.WeeklyChange,
		&i.Notes,
		&i.UpdatedAt,
	)
	return i, err
}

const saveWeight = `-- name: SaveWeight :one
INSERT INTO body_weights (day, weight) VALUES ($1, $2)
ON CONFLICT (user_id, day) DO UPDATE SET weight = excluded.weight, updated_at = now()
RETURNING user_id, day, weight, updated_at
`

type SaveWeightParams struct {
	Day    time.Time
	Weight float64
}

func (q *Queries) SaveWeight(ctx context.Context, arg SaveWeightParams) (BodyWeight, error) {
	row := q.db.QueryRow(ctx, saveWeight, arg.Day, arg.Weight)
	var i BodyWeight
	err := row.Scan(
		&i.UserID,
		&i.Day,
		&i.Weight,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEntry = `-- name: UpdateEntry :one
UPDATE food_entries SET day = $2, meal = $3, grams = $4, amount = $5
WHERE id = $1
RETURNING id, user_id, day, meal, food_id, lmv_number, name, grams, amount, kcal, protein, carbs, fat, fiber, sugars, saturated_fat, salt, logged_by, created_at
`

type UpdateEntryParams struct {
	ID     uuid.UUID
	Day    time.Time
	Meal   string
	Grams  float64
	Amount string
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) (FoodEntry, error) {
	row := q.db.QueryRow(ctx, updateEntry,
		arg.ID,
		arg.Day,
		arg.Meal,
		arg.Grams,
		arg.Amount,
	)
	var i FoodEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Day,
		&i.Meal,
		&i.FoodID,
		&i.LmvNumber,
		&i.Name,
		&i.Grams,
		&i.Amount,
		&i.Kcal,
		&i.Protein,
		&i.Carbs,
		&i.Fat,
		&i.Fiber,
		&i.Sugars,
		&i.SaturatedFat,
		&i.Salt,
		&i.LoggedBy,
		&i.CreatedAt,
	)
	return i, err
}

const weightsBetween = `-- name: WeightsBetween :many
SELECT user_id, day, weight, updated_at FROM body_weights
WHERE day BETWEEN $1 AND $2
ORDER BY day
`

type WeightsBetweenParams struct {
	FromDay time.Time
	ToDay   time.Time
}

func (q *Queries) WeightsBetween(ctx context.Context, arg WeightsBetweenParams) ([]BodyWeight, error) {
	rows, err := q.db.Query(ctx, weightsBetween, arg.FromDay, arg.ToDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BodyWeight{}
	for rows.Next() {
		var i BodyWeight
		if err := rows.Scan(
			&i.UserID,
			&i.Day,
			&i.Weight,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
