// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: batch.go

package plandb

import (
	"context"
	"errors"

	uuid "github.com/gofrs/uuid/v5"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const insertPlannedExercise = `-- name: InsertPlannedExercise :batchexec
INSERT INTO planned_exercises (id, session_id, position, exercise_id, notes, off_arm_percent)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertPlannedExerciseBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertPlannedExerciseParams struct {
	ID            uuid.UUID
	SessionID     uuid.UUID
	Position      int32
	ExerciseID    uuid.UUID
	Notes         string
	OffArmPercent *float64
}

func (q *Queries) InsertPlannedExercise(ctx context.Context, arg []InsertPlannedExerciseParams) *InsertPlannedExerciseBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.SessionID,
			a.Position,
			a.ExerciseID,
			a.Notes,
			a.OffArmPercent,
		}
		batch.Queue(insertPlannedExercise, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertPlannedExerciseBatchResults{br, len(arg), false}
}

func (b *InsertPlannedExerciseBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertPlannedExerciseBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertTarget = `-- name: InsertTarget :batchexec
INSERT INTO planned_targets (id, planned_exercise_id, position, set_type, sets, reps, weight, time, rpe_min, rpe_max, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertTargetBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertTargetParams struct {
	ID                uuid.UUID
	PlannedExerciseID uuid.UUID
	Position          int32
	SetType           string
	Sets              int32
	Reps              *int32
	Weight            *float64
	Time              string
	RpeMin            *float64
	RpeMax            *float64
	Notes             string
}

func (q *Queries) InsertTarget(ctx context.Context, arg []InsertTargetParams) *InsertTargetBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.PlannedExerciseID,
			a.Position,
			a.SetType,
			a.Sets,
			a.Reps,
			a.Weight,
			a.Time,
			a.RpeMin,
			a.RpeMax,
			a.Notes,
		}
		batch.Queue(insertTarget, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertTargetBatchResults{br, len(arg), false}
}

func (b *InsertTargetBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertTargetBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
