// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: plan.sql

package plandb

import (
	"context"
	"encoding/json"
	"time"

	uuid "github.com/gofrs/uuid/v5"
)

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (name, goal, notes, start_date) VALUES ($1, $2, $3, $4) RETURNING id, user_id, name, goal, notes, status, start_date, created_at, updated_at
`

type CreatePlanParams struct {
	Name      string
	Goal      string
	Notes     string
	StartDate *time.Time
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.Name,
		arg.Goal,
		arg.Notes,
		arg.StartDate,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Goal,
		&i.Notes,
		&i.Status,
		&i.StartDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlan = `-- name: DeletePlan :execrows
DELETE FROM plans WHERE id = $1
`

func (q *Queries) DeletePlan(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlan, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM planned_sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSessionExercises = `-- name: DeleteSessionExercises :exec
DELETE FROM planned_exercises WHERE session_id = $1
`

func (q *Queries) DeleteSessionExercises(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionExercises, sessionID)
	return err
}

const getPlan = `-- name: GetPlan :one
SELECT id, user_id, name, goal, notes, status, start_date, created_at, updated_at FROM plans WHERE id = $1
`

func (q *Queries) GetPlan(ctx context.Context, id uuid.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Goal,
		&i.Notes,
		&i.Status,
		&i.StartDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT s.id, s.user_id, s.plan_id, s.position, s.label, s.week, s.day, s.intensity, s.notes, s.status, s.skip_reason, s.completed_at, s.created_at, s.updated_at, w.id AS workout_id
FROM planned_sessions s
LEFT JOIN workouts w ON w.planned_session_id = s.id
WHERE s.id = $1
`

type GetSessionRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	PlanID      uuid.UUID
	Position    int32
	Label       string
	Week        *int32
	Day         *string
	Intensity   *string
	Notes       string
	Status      string
	SkipReason  string
	CompletedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
	WorkoutID   *uuid.UUID
}

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Position,
		&i.Label,
		&i.Week,
		&i.Day,
		&i.Intensity,
		&i.Notes,
		&i.Status,
		&i.SkipReason,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkoutID,
	)
	return i, err
}

const getSessionForUpdate = `-- name: GetSessionForUpdate :one
SELECT id, user_id, plan_id, position, label, week, day, intensity, notes, status, skip_reason, completed_at, created_at, updated_at FROM planned_sessions WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetSessionForUpdate(ctx context.Context, id uuid.UUID) (PlannedSession, error) {
	row := q.db.QueryRow(ctx, getSessionForUpdate, id)
	var i PlannedSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Position,
		&i.Label,
		&i.Week,
		&i.Day,
		&i.Intensity,
		&i.Notes,
		&i.Status,
		&i.SkipReason,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSettingValue = `-- name: GetSettingValue :one
SELECT value FROM settings WHERE key = $1
`

func (q *Queries) GetSettingValue(ctx context.Context, key string) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getSettingValue, key)
	var value json.RawMessage
	err := row.Scan(&value)
	return value, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO planned_sessions (id, plan_id, position, label, week, day, intensity, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertSessionParams struct {
	ID        uuid.UUID
	PlanID    uuid.UUID
	Position  int32
	Label     string
	Week      *int32
	Day       *string
	Intensity *string
	Notes     string
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.PlanID,
		arg.Position,
		arg.Label,
		arg.Week,
		arg.Day,
		arg.Intensity,
		arg.Notes,
	)
	return err
}

const listActualSets = `-- name: ListActualSets :many
SELECT w.planned_session_id AS session_id, we.id AS workout_exercise_id, we.position AS exercise_position,
       we.name, we.planned_exercise_id, ws.position, ws.type, ws.weight, ws.reps, ws.time, ws.rpe, ws.arm,
       ws.target_id, ws.target_seq
FROM workouts w
JOIN workout_exercises we ON we.workout_id = w.id
JOIN workout_sets ws ON ws.workout_exercise_id = we.id
WHERE w.planned_session_id = ANY($1::uuid[])
ORDER BY w.planned_session_id, we.position, ws.position
`

type ListActualSetsRow struct {
	SessionID         *uuid.UUID
	WorkoutExerciseID uuid.UUID
	ExercisePosition  int32
	Name              string
	PlannedExerciseID *uuid.UUID
	Position          int32
	Type              string
	Weight            *float64
	Reps              *int32
	Time              string
	Rpe               *float64
	Arm               string
	TargetID          *uuid.UUID
	TargetSeq         *int32
}

// What was logged in the workouts of these sessions, for the planned versus
// actual comparison.
func (q *Queries) ListActualSets(ctx context.Context, sessionIds []uuid.UUID) ([]ListActualSetsRow, error) {
	rows, err := q.db.Query(ctx, listActualSets, sessionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActualSetsRow{}
	for rows.Next() {
		var i ListActualSetsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.WorkoutExerciseID,
			&i.ExercisePosition,
			&i.Name,
			&i.PlannedExerciseID,
			&i.Position,
			&i.Type,
			&i.Weight,
			&i.Reps,
			&i.Time,
			&i.Rpe,
			&i.Arm,
			&i.TargetID,
			&i.TargetSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlannedExercises = `-- name: ListPlannedExercises :many
SELECT pe.id, pe.user_id, pe.session_id, pe.position, pe.exercise_id, pe.notes, pe.off_arm_percent, e.name AS exercise_name, e.muscle_group, e.type AS exercise_type,
       e.display_type, e.single_arm
FROM planned_exercises pe
JOIN exercises e ON e.id = pe.exercise_id
WHERE pe.session_id = ANY($1::uuid[])
ORDER BY pe.session_id, pe.position
`

type ListPlannedExercisesRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	SessionID     uuid.UUID
	Position      int32
	ExerciseID    uuid.UUID
	Notes         string
	OffArmPercent *float64
	ExerciseName  string
	MuscleGroup   string
	ExerciseType  string
	DisplayType   string
	SingleArm     bool
}

func (q *Queries) ListPlannedExercises(ctx context.Context, sessionIds []uuid.UUID) ([]ListPlannedExercisesRow, error) {
	rows, err := q.db.Query(ctx, listPlannedExercises, sessionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlannedExercisesRow{}
	for rows.Next() {
		var i ListPlannedExercisesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.Position,
			&i.ExerciseID,
			&i.Notes,
			&i.OffArmPercent,
			&i.ExerciseName,
			&i.MuscleGroup,
			&i.ExerciseType,
			&i.DisplayType,
			&i.SingleArm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlans = `-- name: ListPlans :many

SELECT id, user_id, name, goal, notes, status, start_date, created_at, updated_at FROM plans
WHERE ($1::text IS NULL OR status = $1)
ORDER BY created_at DESC
`

// Row level security scopes every query to the signed in user.
func (q *Queries) ListPlans(ctx context.Context, status *string) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlans, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Goal,
			&i.Notes,
			&i.Status,
			&i.StartDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueue = `-- name: ListQueue :many
SELECT s.id, s.user_id, s.plan_id, s.position, s.label, s.week, s.day, s.intensity, s.notes, s.status, s.skip_reason, s.completed_at, s.created_at, s.updated_at, p.name AS plan_name, w.id AS workout_id
FROM planned_sessions s
JOIN plans p ON p.id = s.plan_id
LEFT JOIN workouts w ON w.planned_session_id = s.id
WHERE p.status = 'active' AND s.status IN ('pending', 'in_progress')
ORDER BY p.created_at, s.position
`

type ListQueueRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	PlanID      uuid.UUID
	Position    int32
	Label       string
	Week        *int32
	Day         *string
	Intensity   *string
	Notes       string
	Status      string
	SkipReason  string
	CompletedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
	PlanName    string
	WorkoutID   *uuid.UUID
}

// Sessions still to do in active plans, in the order they are meant to be done.
func (q *Queries) ListQueue(ctx context.Context) ([]ListQueueRow, error) {
	rows, err := q.db.Query(ctx, listQueue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQueueRow{}
	for rows.Next() {
		var i ListQueueRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.Position,
			&i.Label,
			&i.Week,
			&i.Day,
			&i.Intensity,
			&i.Notes,
			&i.Status,
			&i.SkipReason,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PlanName,
			&i.WorkoutID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT s.id, s.user_id, s.plan_id, s.position, s.label, s.week, s.day, s.intensity, s.notes, s.status, s.skip_reason, s.completed_at, s.created_at, s.updated_at, w.id AS workout_id
FROM planned_sessions s
LEFT JOIN workouts w ON w.planned_session_id = s.id
WHERE s.plan_id = ANY($1::uuid[])
ORDER BY s.plan_id, s.position
`

type ListSessionsRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	PlanID      uuid.UUID
	Position    int32
	Label       string
	Week        *int32
	Day         *string
	Intensity   *string
	Notes       string
	Status      string
	SkipReason  string
	CompletedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
	WorkoutID   *uuid.UUID
}

func (q *Queries) ListSessions(ctx context.Context, planIds []uuid.UUID) ([]ListSessionsRow, error) {
	rows, err := q.db.Query(ctx, listSessions, planIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsRow{}
	for rows.Next() {
		var i ListSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.Position,
			&i.Label,
			&i.Week,
			&i.Day,
			&i.Intensity,
			&i.Notes,
			&i.Status,
			&i.SkipReason,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkoutID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargets = `-- name: ListTargets :many
SELECT id, user_id, planned_exercise_id, position, set_type, sets, reps, weight, time, rpe_min, rpe_max, notes FROM planned_targets
WHERE planned_exercise_id = ANY($1::uuid[])
ORDER BY planned_exercise_id, position
`

func (q *Queries) ListTargets(ctx context.Context, plannedExerciseIds []uuid.UUID) ([]PlannedTarget, error) {
	rows, err := q.db.Query(ctx, listTargets, plannedExerciseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlannedTarget{}
	for rows.Next() {
		var i PlannedTarget
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlannedExerciseID,
			&i.Position,
			&i.SetType,
			&i.Sets,
			&i.Reps,
			&i.Weight,
			&i.Time,
			&i.RpeMin,
			&i.RpeMax,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxSessionPosition = `-- name: MaxSessionPosition :one
SELECT coalesce(max(position), -1)::int AS position FROM planned_sessions WHERE plan_id = $1
`

func (q *Queries) MaxSessionPosition(ctx context.Context, planID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, maxSessionPosition, planID)
	var position int32
	err := row.Scan(&position)
	return position, err
}

const setSessionPosition = `-- name: SetSessionPosition :exec
UPDATE planned_sessions SET position = $2, updated_at = now() WHERE id = $1
`

type SetSessionPositionParams struct {
	ID       uuid.UUID
	Position int32
}

func (q *Queries) SetSessionPosition(ctx context.Context, arg SetSessionPositionParams) error {
	_, err := q.db.Exec(ctx, setSessionPosition, arg.ID, arg.Position)
	return err
}

const setSessionStatus = `-- name: SetSessionStatus :exec
UPDATE planned_sessions
SET status = $2, skip_reason = $3, completed_at = $4, updated_at = now()
WHERE id = $1
`

type SetSessionStatusParams struct {
	ID          uuid.UUID
	Status      string
	SkipReason  string
	CompletedAt *time.Time
}

func (q *Queries) SetSessionStatus(ctx context.Context, arg SetSessionStatusParams) error {
	_, err := q.db.Exec(ctx, setSessionStatus,
		arg.ID,
		arg.Status,
		arg.SkipReason,
		arg.CompletedAt,
	)
	return err
}

const shiftSessions = `-- name: ShiftSessions :exec
UPDATE planned_sessions SET position = position + $1::int
WHERE plan_id = $2 AND position > $3::int
`

type ShiftSessionsParams struct {
	By     int32
	PlanID uuid.UUID
	After  int32
}

// Makes room for inserted sessions. The position constraint is deferred, so
// the shift may pass through duplicates within the transaction.
func (q *Queries) ShiftSessions(ctx context.Context, arg ShiftSessionsParams) error {
	_, err := q.db.Exec(ctx, shiftSessions, arg.By, arg.PlanID, arg.After)
	return err
}

const updatePlan = `-- name: UpdatePlan :one
UPDATE plans
SET name = $2, goal = $3, notes = $4, status = $5, start_date = $6, updated_at = now()
WHERE id = $1
RETURNING id, user_id, name, goal, notes, status, start_date, created_at, updated_at
`

type UpdatePlanParams struct {
	ID        uuid.UUID
	Name      string
	Goal      string
	Notes     string
	Status    string
	StartDate *time.Time
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, updatePlan,
		arg.ID,
		arg.Name,
		arg.Goal,
		arg.Notes,
		arg.Status,
		arg.StartDate,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Goal,
		&i.Notes,
		&i.Status,
		&i.StartDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE planned_sessions
SET label = $2, week = $3, day = $4, intensity = $5, notes = $6, updated_at = now()
WHERE id = $1
`

type UpdateSessionParams struct {
	ID        uuid.UUID
	Label     string
	Week      *int32
	Day       *string
	Intensity *string
	Notes     string
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.Exec(ctx, updateSession,
		arg.ID,
		arg.Label,
		arg.Week,
		arg.Day,
		arg.Intensity,
		arg.Notes,
	)
	return err
}
