// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: batch.go

package workoutdb

import (
	"context"
	"errors"

	uuid "github.com/gofrs/uuid/v5"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const insertWorkoutExercise = `-- name: InsertWorkoutExercise :batchexec
INSERT INTO workout_exercises (
  id, workout_id, position, exercise_id, name, muscle_group, type, display_type,
  single_arm, intensity, planned_exercise_id, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertWorkoutExerciseBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertWorkoutExerciseParams struct {
	ID                uuid.UUID
	WorkoutID         uuid.UUID
	Position          int32
	ExerciseID        *uuid.UUID
	Name              string
	MuscleGroup       string
	Type              string
	DisplayType       string
	SingleArm         bool
	Intensity         *string
	PlannedExerciseID *uuid.UUID
	Notes             string
}

func (q *Queries) InsertWorkoutExercise(ctx context.Context, arg []InsertWorkoutExerciseParams) *InsertWorkoutExerciseBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.WorkoutID,
			a.Position,
			a.ExerciseID,
			a.Name,
			a.MuscleGroup,
			a.Type,
			a.DisplayType,
			a.SingleArm,
			a.Intensity,
			a.PlannedExerciseID,
			a.Notes,
		}
		batch.Queue(insertWorkoutExercise, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertWorkoutExerciseBatchResults{br, len(arg), false}
}

func (b *InsertWorkoutExerciseBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertWorkoutExerciseBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertWorkoutSet = `-- name: InsertWorkoutSet :batchexec
INSERT INTO workout_sets (
  workout_exercise_id, position, type, weight, distance, reps, time, rpe, arm, notes, target_id, target_seq
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertWorkoutSetBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertWorkoutSetParams struct {
	WorkoutExerciseID uuid.UUID
	Position          int32
	Type              string
	Weight            *float64
	Distance          *float64
	Reps              *int32
	Time              string
	Rpe               *float64
	Arm               string
	Notes             string
	TargetID          *uuid.UUID
	TargetSeq         *int32
}

func (q *Queries) InsertWorkoutSet(ctx context.Context, arg []InsertWorkoutSetParams) *InsertWorkoutSetBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.WorkoutExerciseID,
			a.Position,
			a.Type,
			a.Weight,
			a.Distance,
			a.Reps,
			a.Time,
			a.Rpe,
			a.Arm,
			a.Notes,
			a.TargetID,
			a.TargetSeq,
		}
		batch.Queue(insertWorkoutSet, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertWorkoutSetBatchResults{br, len(arg), false}
}

func (b *InsertWorkoutSetBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertWorkoutSetBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
