// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: workout.sql

package workoutdb

import (
	"context"
	"time"

	uuid "github.com/gofrs/uuid/v5"
)

const createWorkout = `-- name: CreateWorkout :one
INSERT INTO workouts (id, name, started, ended, notes, planned_session_id, legacy_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, coalesce($8::timestamptz, now()), coalesce($9::timestamptz, now()))
ON CONFLICT (user_id, legacy_id) DO NOTHING
RETURNING id, user_id, name, started, ended, notes, planned_session_id, revision, legacy_id, created_at, updated_at
`

type CreateWorkoutParams struct {
	ID               uuid.UUID
	Name             string
	Started          time.Time
	Ended            *time.Time
	Notes            string
	PlannedSessionID *uuid.UUID
	LegacyID         *int64
	Created          *time.Time
	Updated          *time.Time
}

func (q *Queries) CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (Workout, error) {
	row := q.db.QueryRow(ctx, createWorkout,
		arg.ID,
		arg.Name,
		arg.Started,
		arg.Ended,
		arg.Notes,
		arg.PlannedSessionID,
		arg.LegacyID,
		arg.Created,
		arg.Updated,
	)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Started,
		&i.Ended,
		&i.Notes,
		&i.PlannedSessionID,
		&i.Revision,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkout = `-- name: DeleteWorkout :one
DELETE FROM workouts WHERE id = $1 RETURNING planned_session_id
`

func (q *Queries) DeleteWorkout(ctx context.Context, id uuid.UUID) (*uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteWorkout, id)
	var planned_session_id *uuid.UUID
	err := row.Scan(&planned_session_id)
	return planned_session_id, err
}

const deleteWorkoutExercises = `-- name: DeleteWorkoutExercises :exec
DELETE FROM workout_exercises WHERE workout_id = $1
`

func (q *Queries) DeleteWorkoutExercises(ctx context.Context, workoutID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkoutExercises, workoutID)
	return err
}

const exerciseIDsByName = `-- name: ExerciseIDsByName :many
SELECT id, lower(name)::text AS key FROM exercises WHERE lower(name) = ANY($1::text[])
`

type ExerciseIDsByNameRow struct {
	ID  uuid.UUID
	Key string
}

// Links logged exercises to the exercise list when the client only sent a name.
func (q *Queries) ExerciseIDsByName(ctx context.Context, names []string) ([]ExerciseIDsByNameRow, error) {
	rows, err := q.db.Query(ctx, exerciseIDsByName, names)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExerciseIDsByNameRow{}
	for rows.Next() {
		var i ExerciseIDsByNameRow
		if err := rows.Scan(&i.ID, &i.Key); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkout = `-- name: GetWorkout :one
SELECT id, user_id, name, started, ended, notes, planned_session_id, revision, legacy_id, created_at, updated_at FROM workouts WHERE id = $1
`

func (q *Queries) GetWorkout(ctx context.Context, id uuid.UUID) (Workout, error) {
	row := q.db.QueryRow(ctx, getWorkout, id)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Started,
		&i.Ended,
		&i.Notes,
		&i.PlannedSessionID,
		&i.Revision,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const latestWorkoutByName = `-- name: LatestWorkoutByName :one
SELECT id, user_id, name, started, ended, notes, planned_session_id, revision, legacy_id, created_at, updated_at FROM workouts
WHERE name = $1
  AND ($2::uuid IS NULL OR id <> $2)
ORDER BY started DESC
LIMIT 1
`

type LatestWorkoutByNameParams struct {
	Name      string
	ExcludeID *uuid.UUID
}

func (q *Queries) LatestWorkoutByName(ctx context.Context, arg LatestWorkoutByNameParams) (Workout, error) {
	row := q.db.QueryRow(ctx, latestWorkoutByName, arg.Name, arg.ExcludeID)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Started,
		&i.Ended,
		&i.Notes,
		&i.PlannedSessionID,
		&i.Revision,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkoutExercises = `-- name: ListWorkoutExercises :many
SELECT id, user_id, workout_id, position, exercise_id, name, muscle_group, type, display_type, single_arm, intensity, planned_exercise_id, notes FROM workout_exercises
WHERE workout_id = ANY($1::uuid[])
ORDER BY workout_id, position
`

func (q *Queries) ListWorkoutExercises(ctx context.Context, workoutIds []uuid.UUID) ([]WorkoutExercise, error) {
	rows, err := q.db.Query(ctx, listWorkoutExercises, workoutIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkoutExercise{}
	for rows.Next() {
		var i WorkoutExercise
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkoutID,
			&i.Position,
			&i.ExerciseID,
			&i.Name,
			&i.MuscleGroup,
			&i.Type,
			&i.DisplayType,
			&i.SingleArm,
			&i.Intensity,
			&i.PlannedExerciseID,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutSets = `-- name: ListWorkoutSets :many
SELECT id, user_id, workout_exercise_id, position, type, weight, distance, reps, time, rpe, arm, notes, target_id, target_seq FROM workout_sets
WHERE workout_exercise_id = ANY($1::uuid[])
ORDER BY workout_exercise_id, position
`

func (q *Queries) ListWorkoutSets(ctx context.Context, workoutExerciseIds []uuid.UUID) ([]WorkoutSet, error) {
	rows, err := q.db.Query(ctx, listWorkoutSets, workoutExerciseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkoutSet{}
	for rows.Next() {
		var i WorkoutSet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkoutExerciseID,
			&i.Position,
			&i.Type,
			&i.Weight,
			&i.Distance,
			&i.Reps,
			&i.Time,
			&i.Rpe,
			&i.Arm,
			&i.Notes,
			&i.TargetID,
			&i.TargetSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkouts = `-- name: ListWorkouts :many

SELECT id, user_id, name, started, ended, notes, planned_session_id, revision, legacy_id, created_at, updated_at FROM workouts
WHERE ($1::timestamptz IS NULL OR started >= $1)
  AND ($2::timestamptz IS NULL OR started < $2)
  AND ($3::text IS NULL OR EXISTS (
    SELECT 1 FROM workout_exercises we
    WHERE we.workout_id = workouts.id AND lower(we.name) = lower($3)
  ))
ORDER BY started DESC
LIMIT $4::int
`

type ListWorkoutsParams struct {
	FromTime *time.Time
	ToTime   *time.Time
	Exercise *string
	MaxRows  *int32
}

// Row level security scopes every query to the signed in user. A workout is
// read and written as a whole document: the workout row, its exercises and
// their sets.
func (q *Queries) ListWorkouts(ctx context.Context, arg ListWorkoutsParams) ([]Workout, error) {
	rows, err := q.db.Query(ctx, listWorkouts,
		arg.FromTime,
		arg.ToTime,
		arg.Exercise,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workout{}
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Started,
			&i.Ended,
			&i.Notes,
			&i.PlannedSessionID,
			&i.Revision,
			&i.LegacyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseSession = `-- name: ReleaseSession :exec
UPDATE planned_sessions SET status = 'pending', completed_at = NULL, updated_at = now()
WHERE id = $1 AND status IN ('in_progress', 'completed')
`

// The workout of a session was deleted, so the session is to do again.
func (q *Queries) ReleaseSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, releaseSession, id)
	return err
}

const syncSessionStatus = `-- name: SyncSessionStatus :exec
UPDATE planned_sessions
SET status = CASE WHEN $1::timestamptz IS NULL THEN 'in_progress' ELSE 'completed' END,
    completed_at = $1,
    updated_at = now()
WHERE id = $2 AND status <> 'skipped'
`

type SyncSessionStatusParams struct {
	Ended *time.Time
	ID    uuid.UUID
}

// A planned session follows its workout: in progress until the workout ends,
// completed once it has.
func (q *Queries) SyncSessionStatus(ctx context.Context, arg SyncSessionStatusParams) error {
	_, err := q.db.Exec(ctx, syncSessionStatus, arg.Ended, arg.ID)
	return err
}

const updateWorkout = `-- name: UpdateWorkout :one
UPDATE workouts
SET name = $3, started = $4, ended = $5, notes = $6, revision = revision + 1, updated_at = now()
WHERE id = $1 AND revision = $2
RETURNING id, user_id, name, started, ended, notes, planned_session_id, revision, legacy_id, created_at, updated_at
`

type UpdateWorkoutParams struct {
	ID       uuid.UUID
	Revision int32
	Name     string
	Started  time.Time
	Ended    *time.Time
	Notes    string
}

// Only applies when the caller saw the current revision.
func (q *Queries) UpdateWorkout(ctx context.Context, arg UpdateWorkoutParams) (Workout, error) {
	row := q.db.QueryRow(ctx, updateWorkout,
		arg.ID,
		arg.Revision,
		arg.Name,
		arg.Started,
		arg.Ended,
		arg.Notes,
	)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Started,
		&i.Ended,
		&i.Notes,
		&i.PlannedSessionID,
		&i.Revision,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
