// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: template.sql

package templatedb

import (
	"context"
	"encoding/json"

	uuid "github.com/gofrs/uuid/v5"
)

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (name, doc) VALUES ($1, $2) RETURNING id, user_id, name, doc, legacy_id, created_at, updated_at
`

type CreateTemplateParams struct {
	Name string
	Doc  json.RawMessage
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate, arg.Name, arg.Doc)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Doc,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTemplate = `-- name: DeleteTemplate :execrows
DELETE FROM templates WHERE id = $1
`

func (q *Queries) DeleteTemplate(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTemplate, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTemplate = `-- name: GetTemplate :one
SELECT id, user_id, name, doc, legacy_id, created_at, updated_at FROM templates WHERE id = $1
`

func (q *Queries) GetTemplate(ctx context.Context, id uuid.UUID) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplate, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Doc,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, user_id, name, doc, legacy_id, created_at, updated_at FROM templates ORDER BY created_at DESC
`

func (q *Queries) ListTemplates(ctx context.Context) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Doc,
			&i.LegacyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates SET name = $2, doc = $3, updated_at = now() WHERE id = $1 RETURNING id, user_id, name, doc, legacy_id, created_at, updated_at
`

type UpdateTemplateParams struct {
	ID   uuid.UUID
	Name string
	Doc  json.RawMessage
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, updateTemplate, arg.ID, arg.Name, arg.Doc)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Doc,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
