// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: oauth.sql

package oauthdb

import (
	"context"
	"encoding/json"
	"time"

	uuid "github.com/gofrs/uuid/v5"
)

const createAccessToken = `-- name: CreateAccessToken :exec
INSERT INTO auth.oauth_access_tokens (token_hash, grant_id, expires_at) VALUES ($1, $2, $3)
`

type CreateAccessTokenParams struct {
	TokenHash []byte
	GrantID   uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) error {
	_, err := q.db.Exec(ctx, createAccessToken, arg.TokenHash, arg.GrantID, arg.ExpiresAt)
	return err
}

const createCode = `-- name: CreateCode :exec
INSERT INTO auth.oauth_codes (code_hash, client_id, user_id, redirect_uri, code_challenge, scope, resource, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateCodeParams struct {
	CodeHash      []byte
	ClientID      string
	UserID        uuid.UUID
	RedirectUri   string
	CodeChallenge string
	Scope         string
	Resource      string
	ExpiresAt     time.Time
}

func (q *Queries) CreateCode(ctx context.Context, arg CreateCodeParams) error {
	_, err := q.db.Exec(ctx, createCode,
		arg.CodeHash,
		arg.ClientID,
		arg.UserID,
		arg.RedirectUri,
		arg.CodeChallenge,
		arg.Scope,
		arg.Resource,
		arg.ExpiresAt,
	)
	return err
}

const createGrant = `-- name: CreateGrant :one
INSERT INTO auth.oauth_grants (client_id, user_id, scope, resource, refresh_hash, refresh_expires_at, last_used_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
RETURNING id, client_id, user_id, scope, resource, refresh_hash, previous_refresh_hash, refresh_expires_at, created_at, last_used_at, revoked_at
`

type CreateGrantParams struct {
	ClientID         string
	UserID           uuid.UUID
	Scope            string
	Resource         string
	RefreshHash      []byte
	RefreshExpiresAt time.Time
}

func (q *Queries) CreateGrant(ctx context.Context, arg CreateGrantParams) (AuthOauthGrant, error) {
	row := q.db.QueryRow(ctx, createGrant,
		arg.ClientID,
		arg.UserID,
		arg.Scope,
		arg.Resource,
		arg.RefreshHash,
		arg.RefreshExpiresAt,
	)
	var i AuthOauthGrant
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.UserID,
		&i.Scope,
		&i.Resource,
		&i.RefreshHash,
		&i.PreviousRefreshHash,
		&i.RefreshExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getClient = `-- name: GetClient :one
SELECT client_id, kind, client_name, redirect_uris, metadata, cache_until, created_at, last_used_at FROM auth.oauth_clients WHERE client_id = $1
`

func (q *Queries) GetClient(ctx context.Context, clientID string) (AuthOauthClient, error) {
	row := q.db.QueryRow(ctx, getClient, clientID)
	var i AuthOauthClient
	err := row.Scan(
		&i.ClientID,
		&i.Kind,
		&i.ClientName,
		&i.RedirectUris,
		&i.Metadata,
		&i.CacheUntil,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listGrants = `-- name: ListGrants :many
SELECT g.id, g.client_id, c.client_name, g.scope, g.created_at, g.last_used_at
FROM auth.oauth_grants g
JOIN auth.oauth_clients c ON c.client_id = g.client_id
WHERE g.user_id = $1 AND g.revoked_at IS NULL
ORDER BY g.created_at DESC
`

type ListGrantsRow struct {
	ID         uuid.UUID
	ClientID   string
	ClientName string
	Scope      string
	CreatedAt  time.Time
	LastUsedAt *time.Time
}

func (q *Queries) ListGrants(ctx context.Context, userID uuid.UUID) ([]ListGrantsRow, error) {
	rows, err := q.db.Query(ctx, listGrants, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGrantsRow{}
	for rows.Next() {
		var i ListGrantsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientName,
			&i.Scope,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAccessToken = `-- name: RevokeAccessToken :exec
DELETE FROM auth.oauth_access_tokens WHERE token_hash = $1
`

func (q *Queries) RevokeAccessToken(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeAccessToken, tokenHash)
	return err
}

const revokeGrant = `-- name: RevokeGrant :execrows
UPDATE auth.oauth_grants SET revoked_at = now()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeGrantParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RevokeGrant(ctx context.Context, arg RevokeGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeGrant, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeGrantByPreviousRefresh = `-- name: RevokeGrantByPreviousRefresh :execrows
UPDATE auth.oauth_grants SET revoked_at = now()
WHERE previous_refresh_hash = $1 AND revoked_at IS NULL
`

// A rotated refresh token came back, so somebody else holds one of the two.
func (q *Queries) RevokeGrantByPreviousRefresh(ctx context.Context, previousRefreshHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, revokeGrantByPreviousRefresh, previousRefreshHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeGrantByRefresh = `-- name: RevokeGrantByRefresh :exec
UPDATE auth.oauth_grants SET revoked_at = now()
WHERE (refresh_hash = $1 OR previous_refresh_hash = $1) AND revoked_at IS NULL
`

func (q *Queries) RevokeGrantByRefresh(ctx context.Context, refreshHash []byte) error {
	_, err := q.db.Exec(ctx, revokeGrantByRefresh, refreshHash)
	return err
}

const rotateRefreshToken = `-- name: RotateRefreshToken :one
UPDATE auth.oauth_grants
SET previous_refresh_hash = refresh_hash, refresh_hash = $1,
    refresh_expires_at = $2, last_used_at = now()
WHERE refresh_hash = $3 AND revoked_at IS NULL AND refresh_expires_at > now()
RETURNING id, client_id, user_id, scope, resource, refresh_hash, previous_refresh_hash, refresh_expires_at, created_at, last_used_at, revoked_at
`

type RotateRefreshTokenParams struct {
	NewHash          []byte
	RefreshExpiresAt time.Time
	OldHash          []byte
}

func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (AuthOauthGrant, error) {
	row := q.db.QueryRow(ctx, rotateRefreshToken, arg.NewHash, arg.RefreshExpiresAt, arg.OldHash)
	var i AuthOauthGrant
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.UserID,
		&i.Scope,
		&i.Resource,
		&i.RefreshHash,
		&i.PreviousRefreshHash,
		&i.RefreshExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const takeCode = `-- name: TakeCode :one
DELETE FROM auth.oauth_codes WHERE code_hash = $1 AND expires_at > now() RETURNING code_hash, client_id, user_id, redirect_uri, code_challenge, scope, resource, expires_at
`

// Consumes the code, so it works once.
func (q *Queries) TakeCode(ctx context.Context, codeHash []byte) (AuthOauthCode, error) {
	row := q.db.QueryRow(ctx, takeCode, codeHash)
	var i AuthOauthCode
	err := row.Scan(
		&i.CodeHash,
		&i.ClientID,
		&i.UserID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.Scope,
		&i.Resource,
		&i.ExpiresAt,
	)
	return i, err
}

const touchGrant = `-- name: TouchGrant :exec
UPDATE auth.oauth_grants SET last_used_at = now()
WHERE id = $1 AND (last_used_at IS NULL OR last_used_at < now() - interval '5 minutes')
`

func (q *Queries) TouchGrant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchGrant, id)
	return err
}

const upsertClient = `-- name: UpsertClient :one

INSERT INTO auth.oauth_clients (client_id, kind, client_name, redirect_uris, metadata, cache_until)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (client_id) DO UPDATE
SET client_name = excluded.client_name, redirect_uris = excluded.redirect_uris,
    metadata = excluded.metadata, cache_until = excluded.cache_until
RETURNING client_id, kind, client_name, redirect_uris, metadata, cache_until, created_at, last_used_at
`

type UpsertClientParams struct {
	ClientID     string
	Kind         string
	ClientName   string
	RedirectUris []string
	Metadata     json.RawMessage
	CacheUntil   *time.Time
}

// The auth schema has no row level security. These queries name the user
// they mean wherever a user is involved.
func (q *Queries) UpsertClient(ctx context.Context, arg UpsertClientParams) (AuthOauthClient, error) {
	row := q.db.QueryRow(ctx, upsertClient,
		arg.ClientID,
		arg.Kind,
		arg.ClientName,
		arg.RedirectUris,
		arg.Metadata,
		arg.CacheUntil,
	)
	var i AuthOauthClient
	err := row.Scan(
		&i.ClientID,
		&i.Kind,
		&i.ClientName,
		&i.RedirectUris,
		&i.Metadata,
		&i.CacheUntil,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const verifyAccessToken = `-- name: VerifyAccessToken :one
SELECT g.id AS grant_id, g.user_id, g.scope, g.resource, t.expires_at
FROM auth.oauth_access_tokens t
JOIN auth.oauth_grants g ON g.id = t.grant_id
WHERE t.token_hash = $1 AND t.expires_at > now() AND g.revoked_at IS NULL
`

type VerifyAccessTokenRow struct {
	GrantID   uuid.UUID
	UserID    uuid.UUID
	Scope     string
	Resource  string
	ExpiresAt time.Time
}

func (q *Queries) VerifyAccessToken(ctx context.Context, tokenHash []byte) (VerifyAccessTokenRow, error) {
	row := q.db.QueryRow(ctx, verifyAccessToken, tokenHash)
	var i VerifyAccessTokenRow
	err := row.Scan(
		&i.GrantID,
		&i.UserID,
		&i.Scope,
		&i.Resource,
		&i.ExpiresAt,
	)
	return i, err
}
