// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: account.sql

package accountdb

import (
	"context"
	"encoding/json"
	"time"

	uuid "github.com/gofrs/uuid/v5"
)

const countPasskeys = `-- name: CountPasskeys :one
SELECT count(*) FROM auth.passkeys WHERE user_id = $1
`

func (q *Queries) CountPasskeys(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPasskeys, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnusedRecoveryCodes = `-- name: CountUnusedRecoveryCodes :one
SELECT count(*) FROM auth.recovery_codes WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) CountUnusedRecoveryCodes(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnusedRecoveryCodes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCeremony = `-- name: CreateCeremony :one
INSERT INTO auth.webauthn_ceremonies (kind, user_id, username, webauthn_handle, session_data, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateCeremonyParams struct {
	Kind           string
	UserID         *uuid.UUID
	Username       *string
	WebauthnHandle []byte
	SessionData    json.RawMessage
	ExpiresAt      time.Time
}

func (q *Queries) CreateCeremony(ctx context.Context, arg CreateCeremonyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createCeremony,
		arg.Kind,
		arg.UserID,
		arg.Username,
		arg.WebauthnHandle,
		arg.SessionData,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createPasskey = `-- name: CreatePasskey :exec
INSERT INTO auth.passkeys (
  credential_id, user_id, public_key, attestation_type, aaguid, sign_count,
  transports, backup_eligible, backup_state, name
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreatePasskeyParams struct {
	CredentialID    []byte
	UserID          uuid.UUID
	PublicKey       []byte
	AttestationType string
	Aaguid          []byte
	SignCount       int64
	Transports      []string
	BackupEligible  bool
	BackupState     bool
	Name            string
}

func (q *Queries) CreatePasskey(ctx context.Context, arg CreatePasskeyParams) error {
	_, err := q.db.Exec(ctx, createPasskey,
		arg.CredentialID,
		arg.UserID,
		arg.PublicKey,
		arg.AttestationType,
		arg.Aaguid,
		arg.SignCount,
		arg.Transports,
		arg.BackupEligible,
		arg.BackupState,
		arg.Name,
	)
	return err
}

const createRecoveryCode = `-- name: CreateRecoveryCode :exec
INSERT INTO auth.recovery_codes (user_id, code_hash) VALUES ($1, $2)
`

type CreateRecoveryCodeParams struct {
	UserID   uuid.UUID
	CodeHash []byte
}

func (q *Queries) CreateRecoveryCode(ctx context.Context, arg CreateRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, createRecoveryCode, arg.UserID, arg.CodeHash)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO auth.web_sessions (token_hash, user_id, user_agent, expires_at, absolute_expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateSessionParams struct {
	TokenHash         []byte
	UserID            uuid.UUID
	UserAgent         string
	ExpiresAt         time.Time
	AbsoluteExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.UserAgent,
		arg.ExpiresAt,
		arg.AbsoluteExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :one

INSERT INTO auth.users (id, username, webauthn_handle)
VALUES ($1, $2, $3)
RETURNING id, username, webauthn_handle, created_at
`

type CreateUserParams struct {
	ID             uuid.UUID
	Username       string
	WebauthnHandle []byte
}

// The auth schema has no row level security, because it is read before anyone
// is known. These queries therefore always name the user they mean.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Username, arg.WebauthnHandle)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.WebauthnHandle,
		&i.CreatedAt,
	)
	return i, err
}

const deletePasskey = `-- name: DeletePasskey :execrows
DELETE FROM auth.passkeys WHERE credential_id = $1 AND user_id = $2
`

type DeletePasskeyParams struct {
	CredentialID []byte
	UserID       uuid.UUID
}

func (q *Queries) DeletePasskey(ctx context.Context, arg DeletePasskeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePasskey, arg.CredentialID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRecoveryCodes = `-- name: DeleteRecoveryCodes :exec
DELETE FROM auth.recovery_codes WHERE user_id = $1
`

func (q *Queries) DeleteRecoveryCodes(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecoveryCodes, userID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM auth.web_sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM auth.users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const extendSession = `-- name: ExtendSession :exec
UPDATE auth.web_sessions
SET last_seen_at = now(), expires_at = least($1::timestamptz, absolute_expires_at)
WHERE token_hash = $2
`

type ExtendSessionParams struct {
	ExpiresAt time.Time
	TokenHash []byte
}

func (q *Queries) ExtendSession(ctx context.Context, arg ExtendSessionParams) error {
	_, err := q.db.Exec(ctx, extendSession, arg.ExpiresAt, arg.TokenHash)
	return err
}

const getSession = `-- name: GetSession :one
SELECT token_hash, user_id, user_agent, created_at, last_seen_at, expires_at, absolute_expires_at FROM auth.web_sessions WHERE token_hash = $1 AND expires_at > now()
`

func (q *Queries) GetSession(ctx context.Context, tokenHash []byte) (AuthWebSession, error) {
	row := q.db.QueryRow(ctx, getSession, tokenHash)
	var i AuthWebSession
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.AbsoluteExpiresAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, webauthn_handle, created_at FROM auth.users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.WebauthnHandle,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByHandle = `-- name: GetUserByHandle :one
SELECT id, username, webauthn_handle, created_at FROM auth.users WHERE webauthn_handle = $1
`

func (q *Queries) GetUserByHandle(ctx context.Context, webauthnHandle []byte) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByHandle, webauthnHandle)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.WebauthnHandle,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, webauthn_handle, created_at FROM auth.users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.WebauthnHandle,
		&i.CreatedAt,
	)
	return i, err
}

const listPasskeys = `-- name: ListPasskeys :many
SELECT credential_id, user_id, public_key, attestation_type, aaguid, sign_count, transports, backup_eligible, backup_state, name, created_at, last_used_at FROM auth.passkeys WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListPasskeys(ctx context.Context, userID uuid.UUID) ([]AuthPasskey, error) {
	rows, err := q.db.Query(ctx, listPasskeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthPasskey{}
	for rows.Next() {
		var i AuthPasskey
		if err := rows.Scan(
			&i.CredentialID,
			&i.UserID,
			&i.PublicKey,
			&i.AttestationType,
			&i.Aaguid,
			&i.SignCount,
			&i.Transports,
			&i.BackupEligible,
			&i.BackupState,
			&i.Name,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recoveryCodeUsable = `-- name: RecoveryCodeUsable :one
SELECT EXISTS (
  SELECT 1 FROM auth.recovery_codes WHERE user_id = $1 AND code_hash = $2 AND used_at IS NULL
)
`

type RecoveryCodeUsableParams struct {
	UserID   uuid.UUID
	CodeHash []byte
}

func (q *Queries) RecoveryCodeUsable(ctx context.Context, arg RecoveryCodeUsableParams) (bool, error) {
	row := q.db.QueryRow(ctx, recoveryCodeUsable, arg.UserID, arg.CodeHash)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const renamePasskey = `-- name: RenamePasskey :execrows
UPDATE auth.passkeys SET name = $3 WHERE credential_id = $1 AND user_id = $2
`

type RenamePasskeyParams struct {
	CredentialID []byte
	UserID       uuid.UUID
	Name         string
}

func (q *Queries) RenamePasskey(ctx context.Context, arg RenamePasskeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, renamePasskey, arg.CredentialID, arg.UserID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const seedExercises = `-- name: SeedExercises :exec
INSERT INTO exercises (name, muscle_group, single_arm, type, display_type)
SELECT name, muscle_group, single_arm, type, display_type
FROM jsonb_to_recordset($1::jsonb)
  AS e(name text, muscle_group text, single_arm boolean, type text, display_type text)
`

// Runs as the new user, so user_id comes from the connection.
func (q *Queries) SeedExercises(ctx context.Context, exercises json.RawMessage) error {
	_, err := q.db.Exec(ctx, seedExercises, exercises)
	return err
}

const spendPow = `-- name: SpendPow :execrows
INSERT INTO auth.pow_spent (salt_hash, expires_at) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type SpendPowParams struct {
	SaltHash  []byte
	ExpiresAt time.Time
}

// Records a redeemed proof of work salt. Zero rows means it was spent before.
func (q *Queries) SpendPow(ctx context.Context, arg SpendPowParams) (int64, error) {
	result, err := q.db.Exec(ctx, spendPow, arg.SaltHash, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const takeCeremony = `-- name: TakeCeremony :one
DELETE FROM auth.webauthn_ceremonies
WHERE id = $1 AND kind = $2 AND expires_at > now()
RETURNING id, kind, user_id, username, webauthn_handle, session_data, expires_at
`

type TakeCeremonyParams struct {
	ID   uuid.UUID
	Kind string
}

// Consumes a ceremony, so finishing one twice is impossible.
func (q *Queries) TakeCeremony(ctx context.Context, arg TakeCeremonyParams) (AuthWebauthnCeremony, error) {
	row := q.db.QueryRow(ctx, takeCeremony, arg.ID, arg.Kind)
	var i AuthWebauthnCeremony
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.UserID,
		&i.Username,
		&i.WebauthnHandle,
		&i.SessionData,
		&i.ExpiresAt,
	)
	return i, err
}

const touchPasskey = `-- name: TouchPasskey :exec
UPDATE auth.passkeys
SET sign_count = $3, backup_state = $4, last_used_at = now()
WHERE credential_id = $1 AND user_id = $2
`

type TouchPasskeyParams struct {
	CredentialID []byte
	UserID       uuid.UUID
	SignCount    int64
	BackupState  bool
}

func (q *Queries) TouchPasskey(ctx context.Context, arg TouchPasskeyParams) error {
	_, err := q.db.Exec(ctx, touchPasskey,
		arg.CredentialID,
		arg.UserID,
		arg.SignCount,
		arg.BackupState,
	)
	return err
}

const useRecoveryCode = `-- name: UseRecoveryCode :execrows
UPDATE auth.recovery_codes SET used_at = now()
WHERE user_id = $1 AND code_hash = $2 AND used_at IS NULL
`

type UseRecoveryCodeParams struct {
	UserID   uuid.UUID
	CodeHash []byte
}

func (q *Queries) UseRecoveryCode(ctx context.Context, arg UseRecoveryCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, useRecoveryCode, arg.UserID, arg.CodeHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const usernameTaken = `-- name: UsernameTaken :one
SELECT EXISTS (SELECT 1 FROM auth.users WHERE username = $1)
`

func (q *Queries) UsernameTaken(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, usernameTaken, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
