// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package accountdb

import (
	"encoding/json"
	"time"

	uuid "github.com/gofrs/uuid/v5"
)

type AuthOauthAccessToken struct {
	TokenHash []byte
	GrantID   uuid.UUID
	ExpiresAt time.Time
}

type AuthOauthClient struct {
	ClientID     string
	Kind         string
	ClientName   string
	RedirectUris []string
	Metadata     json.RawMessage
	CacheUntil   *time.Time
	CreatedAt    time.Time
	LastUsedAt   *time.Time
}

type AuthOauthCode struct {
	CodeHash      []byte
	ClientID      string
	UserID        uuid.UUID
	RedirectUri   string
	CodeChallenge string
	Scope         string
	Resource      string
	ExpiresAt     time.Time
}

type AuthOauthGrant struct {
	ID                  uuid.UUID
	ClientID            string
	UserID              uuid.UUID
	Scope               string
	Resource            string
	RefreshHash         []byte
	PreviousRefreshHash []byte
	RefreshExpiresAt    time.Time
	CreatedAt           time.Time
	LastUsedAt          *time.Time
	RevokedAt           *time.Time
}

type AuthPasskey struct {
	CredentialID    []byte
	UserID          uuid.UUID
	PublicKey       []byte
	AttestationType string
	Aaguid          []byte
	SignCount       int64
	Transports      []string
	BackupEligible  bool
	BackupState     bool
	Name            string
	CreatedAt       time.Time
	LastUsedAt      *time.Time
}

type AuthPowSpent struct {
	SaltHash  []byte
	ExpiresAt time.Time
}

type AuthRecoveryCode struct {
	UserID   uuid.UUID
	CodeHash []byte
	UsedAt   *time.Time
}

type AuthUser struct {
	ID             uuid.UUID
	Username       string
	WebauthnHandle []byte
	CreatedAt      time.Time
}

type AuthWebSession struct {
	TokenHash         []byte
	UserID            uuid.UUID
	UserAgent         string
	CreatedAt         time.Time
	LastSeenAt        time.Time
	ExpiresAt         time.Time
	AbsoluteExpiresAt time.Time
}

type AuthWebauthnCeremony struct {
	ID             uuid.UUID
	Kind           string
	UserID         *uuid.UUID
	Username       *string
	WebauthnHandle []byte
	SessionData    json.RawMessage
	ExpiresAt      time.Time
}

type Exercise struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	MuscleGroup string
	Type        string
	DisplayType string
	SingleArm   bool
	Archived    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Plan struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Goal      string
	Notes     string
	Status    string
	StartDate *time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type PlannedExercise struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	SessionID     uuid.UUID
	Position      int32
	ExerciseID    uuid.UUID
	Notes         string
	OffArmPercent *float64
}

type PlannedSession struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	PlanID      uuid.UUID
	Position    int32
	Label       string
	Week        *int32
	Day         *string
	Intensity   *string
	Notes       string
	Status      string
	SkipReason  string
	CompletedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type PlannedTarget struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	PlannedExerciseID uuid.UUID
	Position          int32
	SetType           string
	Sets              int32
	Reps              *int32
	Weight            *float64
	Time              string
	RpeMin            *float64
	RpeMax            *float64
	Notes             string
}

type Setting struct {
	UserID    uuid.UUID
	Key       string
	Value     json.RawMessage
	UpdatedAt time.Time
}

type Template struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Doc       json.RawMessage
	LegacyID  *int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Workout struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	Name             string
	Started          time.Time
	Ended            *time.Time
	Notes            string
	PlannedSessionID *uuid.UUID
	Revision         int32
	LegacyID         *int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type WorkoutExercise struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	WorkoutID         uuid.UUID
	Position          int32
	ExerciseID        *uuid.UUID
	Name              string
	MuscleGroup       string
	Type              string
	DisplayType       string
	SingleArm         bool
	Intensity         *string
	PlannedExerciseID *uuid.UUID
	Notes             string
}

type WorkoutSet struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	WorkoutExerciseID uuid.UUID
	Position          int32
	Type              string
	Weight            *float64
	Distance          *float64
	Reps              *int32
	Time              string
	Rpe               *float64
	Arm               string
	Notes             string
	TargetID          *uuid.UUID
	TargetSeq         *int32
}
