// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: exercise.sql

package exercisedb

import (
	"context"

	uuid "github.com/gofrs/uuid/v5"
)

const createExercise = `-- name: CreateExercise :one
INSERT INTO exercises (name, muscle_group, type, display_type, single_arm)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, muscle_group, type, display_type, single_arm, archived, created_at, updated_at
`

type CreateExerciseParams struct {
	Name        string
	MuscleGroup string
	Type        string
	DisplayType string
	SingleArm   bool
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, createExercise,
		arg.Name,
		arg.MuscleGroup,
		arg.Type,
		arg.DisplayType,
		arg.SingleArm,
	)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.MuscleGroup,
		&i.Type,
		&i.DisplayType,
		&i.SingleArm,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findExerciseByName = `-- name: FindExerciseByName :one
SELECT id, user_id, name, muscle_group, type, display_type, single_arm, archived, created_at, updated_at FROM exercises WHERE lower(name) = lower($1)
`

func (q *Queries) FindExerciseByName(ctx context.Context, lower string) (Exercise, error) {
	row := q.db.QueryRow(ctx, findExerciseByName, lower)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.MuscleGroup,
		&i.Type,
		&i.DisplayType,
		&i.SingleArm,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExercise = `-- name: GetExercise :one
SELECT id, user_id, name, muscle_group, type, display_type, single_arm, archived, created_at, updated_at FROM exercises WHERE id = $1
`

func (q *Queries) GetExercise(ctx context.Context, id uuid.UUID) (Exercise, error) {
	row := q.db.QueryRow(ctx, getExercise, id)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.MuscleGroup,
		&i.Type,
		&i.DisplayType,
		&i.SingleArm,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExercises = `-- name: ListExercises :many

SELECT id, user_id, name, muscle_group, type, display_type, single_arm, archived, created_at, updated_at FROM exercises ORDER BY muscle_group, name
`

// Row level security scopes every query to the signed in user.
func (q *Queries) ListExercises(ctx context.Context) ([]Exercise, error) {
	rows, err := q.db.Query(ctx, listExercises)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Exercise{}
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.MuscleGroup,
			&i.Type,
			&i.DisplayType,
			&i.SingleArm,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameBlockPeriodizationKey = `-- name: RenameBlockPeriodizationKey :exec
UPDATE settings
SET value = (value - $1::text)
    || jsonb_build_object($2::text, value -> $1::text),
    updated_at = now()
WHERE key = 'blockPeriodization_exercises' AND value ? $1::text
`

type RenameBlockPeriodizationKeyParams struct {
	OldName string
	NewName string
}

// Block periodization state is a settings document keyed by exercise name.
func (q *Queries) RenameBlockPeriodizationKey(ctx context.Context, arg RenameBlockPeriodizationKeyParams) error {
	_, err := q.db.Exec(ctx, renameBlockPeriodizationKey, arg.OldName, arg.NewName)
	return err
}

const renameExerciseSnapshots = `-- name: RenameExerciseSnapshots :exec
UPDATE workout_exercises SET name = $1
WHERE exercise_id = $2 OR lower(name) = lower($3)
`

type RenameExerciseSnapshotsParams struct {
	NewName    string
	ExerciseID *uuid.UUID
	OldName    string
}

// History is keyed by name, so a rename carries it along.
func (q *Queries) RenameExerciseSnapshots(ctx context.Context, arg RenameExerciseSnapshotsParams) error {
	_, err := q.db.Exec(ctx, renameExerciseSnapshots, arg.NewName, arg.ExerciseID, arg.OldName)
	return err
}

const suggestExercises = `-- name: SuggestExercises :many
SELECT name FROM exercises
WHERE similarity(name, $1::text) > 0.2
ORDER BY similarity(name, $1::text) DESC
LIMIT 5
`

// Closest names first, for an unknown name typed by a person or a model.
func (q *Queries) SuggestExercises(ctx context.Context, name string) ([]string, error) {
	rows, err := q.db.Query(ctx, suggestExercises, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExercise = `-- name: UpdateExercise :one
UPDATE exercises
SET name = $2, muscle_group = $3, type = $4, display_type = $5, single_arm = $6,
    archived = $7, updated_at = now()
WHERE id = $1
RETURNING id, user_id, name, muscle_group, type, display_type, single_arm, archived, created_at, updated_at
`

type UpdateExerciseParams struct {
	ID          uuid.UUID
	Name        string
	MuscleGroup string
	Type        string
	DisplayType string
	SingleArm   bool
	Archived    bool
}

func (q *Queries) UpdateExercise(ctx context.Context, arg UpdateExerciseParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, updateExercise,
		arg.ID,
		arg.Name,
		arg.MuscleGroup,
		arg.Type,
		arg.DisplayType,
		arg.SingleArm,
		arg.Archived,
	)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.MuscleGroup,
		&i.Type,
		&i.DisplayType,
		&i.SingleArm,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
