// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: food.sql

package fooddb

import (
	"context"
	"encoding/json"
	"time"

	uuid "github.com/gofrs/uuid/v5"
)

const createFood = `-- name: CreateFood :one
INSERT INTO foods (name, brand, gtin, kcal, protein, carbs, fat, fiber, sugars, saturated_fat, salt, notes,
                   search_terms)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, user_id, name, brand, gtin, kcal, protein, carbs, fat, fiber, sugars, saturated_fat, salt, notes, created_at, updated_at, search_terms, search
`

type CreateFoodParams struct {
	Name         string
	Brand        string
	Gtin         *string
	Kcal         float64
	Protein      float64
	Carbs        float64
	Fat          float64
	Fiber        *float64
	Sugars       *float64
	SaturatedFat *float64
	Salt         *float64
	Notes        string
	SearchTerms  string
}

func (q *Queries) CreateFood(ctx context.Context, arg CreateFoodParams) (Food, error) {
	row := q.db.QueryRow(ctx, createFood,
		arg.Name,
		arg.Brand,
		arg.Gtin,
		arg.Kcal,
		arg.Protein,
		arg.Carbs,
		arg.Fat,
		arg.Fiber,
		arg.Sugars,
		arg.SaturatedFat,
		arg.Salt,
		arg.Notes,
		arg.SearchTerms,
	)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Brand,
		&i.Gtin,
		&i.Kcal,
		&i.Protein,
		&i.Carbs,
		&i.Fat,
		&i.Fiber,
		&i.Sugars,
		&i.SaturatedFat,
		&i.Salt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchTerms,
		&i.Search,
	)
	return i, err
}

const deleteFood = `-- name: DeleteFood :execrows
DELETE FROM foods WHERE id = $1
`

func (q *Queries) DeleteFood(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFood, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePortion = `-- name: DeletePortion :execrows
DELETE FROM food_portions WHERE id = $1
`

func (q *Queries) DeletePortion(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePortion, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFood = `-- name: GetFood :one
SELECT id, user_id, name, brand, gtin, kcal, protein, carbs, fat, fiber, sugars, saturated_fat, salt, notes, created_at, updated_at, search_terms, search FROM foods WHERE id = $1
`

func (q *Queries) GetFood(ctx context.Context, id uuid.UUID) (Food, error) {
	row := q.db.QueryRow(ctx, getFood, id)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Brand,
		&i.Gtin,
		&i.Kcal,
		&i.Protein,
		&i.Carbs,
		&i.Fat,
		&i.Fiber,
		&i.Sugars,
		&i.SaturatedFat,
		&i.Salt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchTerms,
		&i.Search,
	)
	return i, err
}

const getLMVFood = `-- name: GetLMVFood :one
SELECT number, name, food_group, kcal, protein, carbs, fat, fiber, sugars, saturated_fat, salt, nutrients, retired, updated_at, search_terms, search FROM lmv.foods WHERE number = $1
`

func (q *Queries) GetLMVFood(ctx context.Context, number int32) (LmvFood, error) {
	row := q.db.QueryRow(ctx, getLMVFood, number)
	var i LmvFood
	err := row.Scan(
		&i.Number,
		&i.Name,
		&i.FoodGroup,
		&i.Kcal,
		&i.Protein,
		&i.Carbs,
		&i.Fat,
		&i.Fiber,
		&i.Sugars,
		&i.SaturatedFat,
		&i.Salt,
		&i.Nutrients,
		&i.Retired,
		&i.UpdatedAt,
		&i.SearchTerms,
		&i.Search,
	)
	return i, err
}

const insertRelease = `-- name: InsertRelease :exec
INSERT INTO lmv.releases (version, sha256, foods, vocabulary) VALUES ($1, $2, $3, $4)
`

type InsertReleaseParams struct {
	Version    string
	Sha256     []byte
	Foods      int32
	Vocabulary []string
}

func (q *Queries) InsertRelease(ctx context.Context, arg InsertReleaseParams) error {
	_, err := q.db.Exec(ctx, insertRelease,
		arg.Version,
		arg.Sha256,
		arg.Foods,
		arg.Vocabulary,
	)
	return err
}

const latestRelease = `-- name: LatestRelease :one

SELECT id, version, imported_at FROM lmv.releases ORDER BY imported_at DESC LIMIT 1
`

type LatestReleaseRow struct {
	ID         uuid.UUID
	Version    string
	ImportedAt time.Time
}

// The user's own foods are scoped by row level security. The lmv schema is
// shared by everyone.
func (q *Queries) LatestRelease(ctx context.Context) (LatestReleaseRow, error) {
	row := q.db.QueryRow(ctx, latestRelease)
	var i LatestReleaseRow
	err := row.Scan(&i.ID, &i.Version, &i.ImportedAt)
	return i, err
}

const listFoods = `-- name: ListFoods :many
SELECT id, user_id, name, brand, gtin, kcal, protein, carbs, fat, fiber, sugars, saturated_fat, salt, notes, created_at, updated_at, search_terms, search FROM foods ORDER BY lower(name), lower(brand)
`

func (q *Queries) ListFoods(ctx context.Context) ([]Food, error) {
	rows, err := q.db.Query(ctx, listFoods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Food{}
	for rows.Next() {
		var i Food
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Brand,
			&i.Gtin,
			&i.Kcal,
			&i.Protein,
			&i.Carbs,
			&i.Fat,
			&i.Fiber,
			&i.Sugars,
			&i.SaturatedFat,
			&i.Salt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchTerms,
			&i.Search,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const portionsOf = `-- name: PortionsOf :many
SELECT id, user_id, food_id, lmv_number, name, grams FROM food_portions
WHERE food_id = ANY($1::uuid[]) OR lmv_number = ANY($2::int[])
ORDER BY grams, name
`

type PortionsOfParams struct {
	FoodIds    []uuid.UUID
	LmvNumbers []int32
}

// The portions of the foods named, by either kind of reference.
func (q *Queries) PortionsOf(ctx context.Context, arg PortionsOfParams) ([]FoodPortion, error) {
	rows, err := q.db.Query(ctx, portionsOf, arg.FoodIds, arg.LmvNumbers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FoodPortion{}
	for rows.Next() {
		var i FoodPortion
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FoodID,
			&i.LmvNumber,
			&i.Name,
			&i.Grams,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseImported = `-- name: ReleaseImported :one
SELECT EXISTS (SELECT 1 FROM lmv.releases WHERE sha256 = $1)
`

func (q *Queries) ReleaseImported(ctx context.Context, sha256 []byte) (bool, error) {
	row := q.db.QueryRow(ctx, releaseImported, sha256)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const releaseVocabulary = `-- name: ReleaseVocabulary :one
SELECT vocabulary FROM lmv.releases WHERE id = $1
`

func (q *Queries) ReleaseVocabulary(ctx context.Context, id uuid.UUID) ([]string, error) {
	row := q.db.QueryRow(ctx, releaseVocabulary, id)
	var vocabulary []string
	err := row.Scan(&vocabulary)
	return vocabulary, err
}

const retireLMVFoods = `-- name: RetireLMVFoods :execrows
UPDATE lmv.foods SET retired = true, updated_at = now()
WHERE NOT retired AND NOT (number = ANY($1::int[]))
`

// Foods the new release no longer has.
func (q *Queries) RetireLMVFoods(ctx context.Context, keep []int32) (int64, error) {
	result, err := q.db.Exec(ctx, retireLMVFoods, keep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveAlias = `-- name: SaveAlias :exec
INSERT INTO food_aliases (alias, food_id, lmv_number) VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type SaveAliasParams struct {
	Alias     string
	FoodID    *uuid.UUID
	LmvNumber *int32
}

// Remembers what the user called a food. Saying it again changes nothing.
func (q *Queries) SaveAlias(ctx context.Context, arg SaveAliasParams) error {
	_, err := q.db.Exec(ctx, saveAlias, arg.Alias, arg.FoodID, arg.LmvNumber)
	return err
}

const savePortion = `-- name: SavePortion :one
INSERT INTO food_portions (food_id, lmv_number, name, grams)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, coalesce(food_id::text, lmv_number::text), lower(name))
DO UPDATE SET grams = excluded.grams, name = excluded.name
RETURNING id, user_id, food_id, lmv_number, name, grams
`

type SavePortionParams struct {
	FoodID    *uuid.UUID
	LmvNumber *int32
	Name      string
	Grams     float64
}

// A portion is identified by its food and name, so saving one again changes
// its weight.
func (q *Queries) SavePortion(ctx context.Context, arg SavePortionParams) (FoodPortion, error) {
	row := q.db.QueryRow(ctx, savePortion,
		arg.FoodID,
		arg.LmvNumber,
		arg.Name,
		arg.Grams,
	)
	var i FoodPortion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FoodID,
		&i.LmvNumber,
		&i.Name,
		&i.Grams,
	)
	return i, err
}

const searchFoods = `-- name: SearchFoods :many
WITH q AS (
  SELECT to_tsquery('swedish', $3::text) AS tsq
),
history AS (
  SELECT food_id, lmv_number, count(*)::int AS uses
  FROM food_entries
  WHERE day > current_date - 90
  GROUP BY food_id, lmv_number
),
aliased AS (
  SELECT food_id, lmv_number, bool_or(lower(alias) = lower($1::text)) AS exact
  FROM food_aliases
  WHERE NOT EXISTS (SELECT 1 FROM unnest($4::text[]) w WHERE alias NOT ILIKE '%' || w || '%')
  GROUP BY food_id, lmv_number
),
matches AS (
  SELECT 'mine'::text AS source, f.id, NULL::int AS lmv_number, f.name, f.brand,
         ''::text AS food_group, f.kcal, f.protein, f.carbs, f.fat, f.fiber, f.sugars,
         f.saturated_fat, f.salt, 1 AS source_rank,
         coalesce(f.gtin = $1::text, false) AS barcode,
         coalesce(f.search @@ q.tsq, false)
           OR NOT EXISTS (SELECT 1 FROM unnest($4::text[]) w
                          WHERE f.name || ' ' || f.brand NOT ILIKE '%' || w || '%') AS has_words,
         coalesce(ts_rank(f.search, q.tsq), 0) AS rank
  FROM foods f, q
  WHERE f.search @@ q.tsq
     OR NOT EXISTS (SELECT 1 FROM unnest($4::text[]) w
                    WHERE f.name || ' ' || f.brand NOT ILIKE '%' || w || '%')
     OR word_similarity($1::text, f.name) > 0.5
     OR f.gtin = $1::text
     OR f.id IN (SELECT food_id FROM aliased)
  UNION ALL
  SELECT 'lmv', NULL::uuid, l.number, l.name, '', l.food_group, l.kcal, l.protein, l.carbs, l.fat,
         l.fiber, l.sugars, l.saturated_fat, l.salt, 2,
         false,
         coalesce(l.search @@ q.tsq, false)
           OR NOT EXISTS (SELECT 1 FROM unnest($4::text[]) w WHERE l.name NOT ILIKE '%' || w || '%'),
         coalesce(ts_rank(l.search, q.tsq), 0)
  FROM lmv.foods l, q
  WHERE NOT l.retired
    AND (l.search @@ q.tsq
         OR NOT EXISTS (SELECT 1 FROM unnest($4::text[]) w WHERE l.name NOT ILIKE '%' || w || '%')
         OR word_similarity($1::text, l.name) > 0.5
         OR l.number IN (SELECT lmv_number FROM aliased))
)
SELECT m.source, coalesce(m.id::text, m.lmv_number::text)::text AS ref, m.name, m.brand, m.food_group,
       m.kcal, m.protein, m.carbs, m.fat, m.fiber, m.sugars, m.saturated_fat, m.salt,
       coalesce(h.uses, 0)::int AS uses
FROM matches m
LEFT JOIN history h ON h.food_id = m.id OR h.lmv_number = m.lmv_number
LEFT JOIN aliased a ON a.food_id = m.id OR a.lmv_number = m.lmv_number
ORDER BY (m.barcode OR coalesce(a.exact, false)) DESC,
         (m.has_words OR a.exact IS NOT NULL) DESC,
         coalesce(h.uses, 0) DESC,
         m.source_rank,
         m.rank DESC,
         (m.name ILIKE $1::text || '%') DESC,
         word_similarity($1::text, m.name) DESC,
         length(m.name), m.name
LIMIT $2
`

type SearchFoodsParams struct {
	Query      string
	MaxResults int32
	Tsquery    *string
	Words      []string
}

type SearchFoodsRow struct {
	Source       string
	Ref          string
	Name         string
	Brand        string
	FoodGroup    string
	Kcal         float64
	Protein      float64
	Carbs        float64
	Fat          float64
	Fiber        *float64
	Sugars       *float64
	SaturatedFat *float64
	Salt         *float64
	Uses         int32
}

// The user's foods and Livsmedelsverket's in one list, best match first:
//  1. what the user has called exactly this (an alias), or its barcode,
//  2. foods holding every word, by Swedish stem, compound part or as part of
//     the name, before fuzzy matches that catch typos,
//  3. within those, what the user logged most in the last 90 days, then the
//     user's own foods, then the text search rank and the closest name.
//
// words are the query's words escaped for LIKE, tsquery the same search for
// to_tsquery, null when it has no words.
// One reference column, since a union's column takes its nullability from
// the first branch: the food's id for the user's own, the number for lmv.
func (q *Queries) SearchFoods(ctx context.Context, arg SearchFoodsParams) ([]SearchFoodsRow, error) {
	rows, err := q.db.Query(ctx, searchFoods,
		arg.Query,
		arg.MaxResults,
		arg.Tsquery,
		arg.Words,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchFoodsRow{}
	for rows.Next() {
		var i SearchFoodsRow
		if err := rows.Scan(
			&i.Source,
			&i.Ref,
			&i.Name,
			&i.Brand,
			&i.FoodGroup,
			&i.Kcal,
			&i.Protein,
			&i.Carbs,
			&i.Fat,
			&i.Fiber,
			&i.Sugars,
			&i.SaturatedFat,
			&i.Salt,
			&i.Uses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFood = `-- name: UpdateFood :one
UPDATE foods
SET name = $2, brand = $3, gtin = $4, kcal = $5, protein = $6, carbs = $7, fat = $8, fiber = $9,
    sugars = $10, saturated_fat = $11, salt = $12, notes = $13, search_terms = $14, updated_at = now()
WHERE id = $1
RETURNING id, user_id, name, brand, gtin, kcal, protein, carbs, fat, fiber, sugars, saturated_fat, salt, notes, created_at, updated_at, search_terms, search
`

type UpdateFoodParams struct {
	ID           uuid.UUID
	Name         string
	Brand        string
	Gtin         *string
	Kcal         float64
	Protein      float64
	Carbs        float64
	Fat          float64
	Fiber        *float64
	Sugars       *float64
	SaturatedFat *float64
	Salt         *float64
	Notes        string
	SearchTerms  string
}

func (q *Queries) UpdateFood(ctx context.Context, arg UpdateFoodParams) (Food, error) {
	row := q.db.QueryRow(ctx, updateFood,
		arg.ID,
		arg.Name,
		arg.Brand,
		arg.Gtin,
		arg.Kcal,
		arg.Protein,
		arg.Carbs,
		arg.Fat,
		arg.Fiber,
		arg.Sugars,
		arg.SaturatedFat,
		arg.Salt,
		arg.Notes,
		arg.SearchTerms,
	)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Brand,
		&i.Gtin,
		&i.Kcal,
		&i.Protein,
		&i.Carbs,
		&i.Fat,
		&i.Fiber,
		&i.Sugars,
		&i.SaturatedFat,
		&i.Salt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchTerms,
		&i.Search,
	)
	return i, err
}

const upsertLMVFood = `-- name: UpsertLMVFood :exec
INSERT INTO lmv.foods (number, name, food_group, kcal, protein, carbs, fat, fiber, sugars,
                       saturated_fat, salt, nutrients, search_terms, retired, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, false, now())
ON CONFLICT (number) DO UPDATE
SET name = excluded.name, food_group = excluded.food_group, kcal = excluded.kcal,
    protein = excluded.protein, carbs = excluded.carbs, fat = excluded.fat, fiber = excluded.fiber,
    sugars = excluded.sugars, saturated_fat = excluded.saturated_fat, salt = excluded.salt,
    nutrients = excluded.nutrients, search_terms = excluded.search_terms, retired = false, updated_at = now()
`

type UpsertLMVFoodParams struct {
	Number       int32
	Name         string
	FoodGroup    string
	Kcal         float64
	Protein      float64
	Carbs        float64
	Fat          float64
	Fiber        *float64
	Sugars       *float64
	SaturatedFat *float64
	Salt         *float64
	Nutrients    json.RawMessage
	SearchTerms  string
}

func (q *Queries) UpsertLMVFood(ctx context.Context, arg UpsertLMVFoodParams) error {
	_, err := q.db.Exec(ctx, upsertLMVFood,
		arg.Number,
		arg.Name,
		arg.FoodGroup,
		arg.Kcal,
		arg.Protein,
		arg.Carbs,
		arg.Fat,
		arg.Fiber,
		arg.Sugars,
		arg.SaturatedFat,
		arg.Salt,
		arg.Nutrients,
		arg.SearchTerms,
	)
	return err
}
