// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: setting.sql

package settingdb

import (
	"context"
	"encoding/json"
)

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM settings WHERE key = $1
`

func (q *Queries) DeleteSetting(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteSetting, key)
	return err
}

const listSettings = `-- name: ListSettings :many
SELECT key, value FROM settings ORDER BY key
`

type ListSettingsRow struct {
	Key   string
	Value json.RawMessage
}

func (q *Queries) ListSettings(ctx context.Context) ([]ListSettingsRow, error) {
	rows, err := q.db.Query(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSettingsRow{}
	for rows.Next() {
		var i ListSettingsRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putSetting = `-- name: PutSetting :exec
INSERT INTO settings (key, value) VALUES ($1, $2)
ON CONFLICT (user_id, key) DO UPDATE SET value = excluded.value, updated_at = now()
`

type PutSettingParams struct {
	Key   string
	Value json.RawMessage
}

func (q *Queries) PutSetting(ctx context.Context, arg PutSettingParams) error {
	_, err := q.db.Exec(ctx, putSetting, arg.Key, arg.Value)
	return err
}
