// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: system.sql

package systemdb

import (
	"context"
	"time"
)

const databaseTime = `-- name: DatabaseTime :one
SELECT now()::timestamptz AS now
`

// Proves the database answers, for the health check.
func (q *Queries) DatabaseTime(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, databaseTime)
	var now time.Time
	err := row.Scan(&now)
	return now, err
}
