// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: maintenance.sql

package maintenancedb

import (
	"context"
)

const pruneAccessTokens = `-- name: PruneAccessTokens :execrows
DELETE FROM auth.oauth_access_tokens WHERE expires_at < now()
`

func (q *Queries) PruneAccessTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, pruneAccessTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneCeremonies = `-- name: PruneCeremonies :execrows

DELETE FROM auth.webauthn_ceremonies WHERE expires_at < now()
`

// Rows that can never be used again. Each delete is bounded by an index on
// the expiry, and the auth schema has no row level security, so one pass
// covers every user.
func (q *Queries) PruneCeremonies(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, pruneCeremonies)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneClients = `-- name: PruneClients :execrows
DELETE FROM auth.oauth_clients c
WHERE c.created_at < now() - interval '7 days'
  AND NOT EXISTS (SELECT 1 FROM auth.oauth_grants g WHERE g.client_id = c.client_id)
`

// A dynamically registered client that never got a grant within a week was
// abandoned, and open registration would otherwise grow without bound.
func (q *Queries) PruneClients(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, pruneClients)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneCodes = `-- name: PruneCodes :execrows
DELETE FROM auth.oauth_codes WHERE expires_at < now()
`

func (q *Queries) PruneCodes(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, pruneCodes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneGrants = `-- name: PruneGrants :execrows
DELETE FROM auth.oauth_grants
WHERE revoked_at < now() - interval '30 days' OR refresh_expires_at < now() - interval '30 days'
`

// A revoked grant or one whose refresh token ran out cannot come back.
func (q *Queries) PruneGrants(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, pruneGrants)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const prunePow = `-- name: PrunePow :execrows
DELETE FROM auth.pow_spent WHERE expires_at < now()
`

func (q *Queries) PrunePow(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, prunePow)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneSessions = `-- name: PruneSessions :execrows
DELETE FROM auth.web_sessions WHERE expires_at < now() OR absolute_expires_at < now()
`

func (q *Queries) PruneSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, pruneSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
